"""Ajout table images

Revision ID: 3967675dbefd
Revises: 
Create Date: 2025-06-26 14:23:02.135649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3967675dbefd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('personnage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personnage_id'], ['personnages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'relations', 'personnages', ['perso_1_id'], ['id'])
    op.create_foreign_key(None, 'relations', 'personnages', ['perso_2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_table('images')
    # ### end Alembic commands ###
